spring:
  datasource:
#
#    #      Localhost Oracle
#    #      url: jdbc:oracle:thin:@//localhost:11521/OperaUserAccessRequisition
#    #      username: OperaUserAccessRequisitionUser
#    #      password: qwerty2022
#    #      driver-class-name: oracle.jdbc.OracleDriver
#
    #CONEXION REMOTA
#    #url: jdbc:sqlserver://127.0.0.1:14000;databaseName=TestDatabase
#
#    #CONEXION LOCALES
     url: jdbc:sqlserver://localhost:3036;databaseName=TestDatabase;encrypt=true;trustServerCertificate=true
     username: Olan
     password: Xb0xisCool.
#    #username: Olanc
#    #password: Olanc178
#
#
     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    # driver-class-name: com.mysql.cj.jdbc.Driver
#
  jpa:
     hibernate:
      ddl-auto: create #create update none
     properties:
      hibernate:
        #dialect: org.hibernate.dialect.SQLServerDialect
#        #dialect: org.hibernate.dialect.MySQLDialect
#
        jdbc:
          time_zone: UTC
#
##logging.level:
##Uncomment for extensive SQL logging
##org.hibernate.SQL: DEBUG
##org.hibernate.type: TRACE
##org.hibernate.search.fulltext_query: DEBUG
#
#
