spring:
  application:
    name: expedienteclinico
  jmx:
    default-domain: expedienteclinico
  profiles:
    active: dev # Cambiar a 'prod' en el servidor final
  main:
    allow-bean-definition-overriding: true

  # ALERTA: Esta sección de sesión debe eliminarse en la Fase 3 (Migración a JWT puro)
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql

  flyway:
    enabled: false # APAGADO CRÍTICO: Nosotros controlaremos Flyway por código.

  # Configuración de Vistas
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/views/
    suffix: .html
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Configuración Global de Base de Datos y Pool
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: HikariPoolBooks

  # Configuración Global JPA
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # Se ELIMINA la propiedad 'dialect'
        jdbc:
          time_zone: UTC
        # Futura inyección para Multi-Tenancy (Fase 2)
        # multiTenancy: SCHEMA
        # tenant_identifier_resolver: ...
        # multi_tenant_connection_provider: ...

  # Si usas Spring Batch
  batch:
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-sqlserver.sql

server:
  port: 8080 # O el puerto que hayas borrado en la captura
  servlet:
    context-path: / # Recomiendo cambiar esto a /api posteriormente
    session:
      timeout: 43200

# Variables de entorno personalizadas
GA:
  app:
    publicURL: GA-QR/