spring:

  datasource:
    #        Localhost
     url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=RPBI;encrypt=true;trustServerCertificate=true;}
     username: ${DB_USERNAME:Darick}
     password: ${DB_PASS:Darick471}
     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect

        jdbc:
          time_zone: UTC

#logging.level:
#Uncomment for extensive SQL logging
#org.hibernate.SQL: DEBUG
#org.hibernate.type: TRACE
#org.hibernate.search.fulltext_query: DEBUG