spring.application.name=expedienteclinico

spring.jmx.default-domain = expedienteclinico
server.servlet.context-path= /

spring.jpa.show-sql=true
spring.h2.console.enabled=true
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2019Dialect
server.port=8080
logging.level.com.OperaUserAccessRequisitionForm=DEBUG

#SESSION PROPERTIES
spring.session.store-type=jdbc
# Session timeout. If a duration suffix is not specified, seconds are used.
server.servlet.session.timeout=43200
# Database schema initialization mode.
spring.session.jdbc.initialize-schema=always
# Name of the database table used to store sessions.
spring.session.jdbc.table-name=SPRING_SESSION
# Path to the SQL file to use to initialize the database schema.
spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-@@platform@@.sql

#spring.thymeleaf.cache=false
#spring.thymeleaf.enabled=true
#spring.thymeleaf.prefix=classpath:/views/
#spring.thymeleaf.suffix=.html

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# JWT
app.jwtSecret=3c9Ygrvj8CjCiGDwY5RHxUIsluPrHxWQ
app.jwtExpirationMs=86400000

# Google Authenticator
GA.app.publicURL=GA-QR/

# HikariCP settings
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=HikariPoolBooks

# JPA settings
#spring.jpa.hibernate.use-new-id-generator-mappings=false
#spring.jpa.hibernate.ddl-auto=create

spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
hibernate.ddl-auto=none

spring.batch.schema=classpath:org/springframework/batch/core/schema-sqlserver.sql


spring.main.allow-bean-definition-overriding=true

spring.jpa.hibernate.ddl-auto=update
