server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: nexus-core-server

  # Desactivar Flyway temporalmente según directiva de desarrollo
  flyway:
    enabled: false

  rabbitmq:
    host: ${NEXUS_RABBITMQ_HOST:localhost}
    port: ${NEXUS_RABBITMQ_PORT:5672}
    username: ${NEXUS_RABBITMQ_USER:nexus_admin}
    password: ${NEXUS_RABBITMQ_PASS:secure_local_pass}
    virtual-host: ${NEXUS_RABBITMQ_VHOST:nexus_tenant_vhost}
    template:
      retry:
        enabled: true
        initial-interval: 3000ms
        max-interval: 15000ms
        multiplier: 2.0
        max-attempts: 5
      listener:
        simple:
          retry:
            enabled: true
            initial-interval: 3000ms
            max-attempts: 5
            multiplier: 2.0

  datasource:
    #url: jdbc:mysql://${NEXUS_DB_HOST:localhost}:${NEXUS_DB_PORT:3306}/his_master?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://${NEXUS_DB_HOST:localhost}:${NEXUS_DB_PORT:3306}/his_master?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #username: ${NEXUS_DB_USER:his_master_admin}
    username: ${NEXUS_DB_USER:Olan}
    #password: ${NEXUS_DB_PASS:Darick471}
    password: ${NEXUS_DB_PASS:Xb0xisCool.}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: NexusCoreMasterPool

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: WARN
    com.nexusbusiness: INFO  # Obliga a mostrar los log.info() de tus clases
    org.flywaydb: INFO
    # Suprimir ruidos excesivos de reconexión de RabbitMQ manteniendo solo alertas críticas
    org.springframework.amqp: FATAL